<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:include filename="physical_properties.xacro"/>
    <xacro:include filename="inertial_macros.xacro"/>

    <!-- Here the macros for the wheel and roller creation are defined -->
    
    <xacro:macro name="roller" params="prefix suffix theta roller_orientation">
        <link name="${prefix}_${suffix}_roller">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="0.0082" length="0.045"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="0.0082" length="0.045"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 0"/>
                <mass value="0.001" />
                <inertia ixx="8.72e-8" ixy="0.0" ixz="0.0"
                        iyy="8.72e-8" iyz="0.0"
                        izz="6.722e-9" />
            </inertial>


        </link>
        <joint name="${prefix}_${suffix}_roller_joint" type="continuous">
                <axis xyz="0 0 1" />
                <parent link="${prefix}_wheel"/>
                <child link="${prefix}_${suffix}_roller"/>
                <origin xyz="${cos(theta)*wheel_radius} ${sin(theta)*wheel_radius} 0" rpy="0 ${roller_orientation} ${(pi/2)+theta}"/>
        </joint>

        <gazebo reference="${prefix}_${suffix}_roller">
            <mu1>100000000000000.0</mu1>
            <mu2>100000000000000.0</mu2>
        </gazebo>

    </xacro:macro>


    <xacro:macro name="wheel" params="prefix suffix radius length mass offset_x offset_y offset_z wheel_roller_orientation">
        <link name="${prefix}_${suffix}_wheel">
            
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name="orange"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz = "0 0 0"/>
                <mass value="0.4"/>
                <inertia ixx="0.000239" ixy="0.0" ixz="0.0"
                        iyy="0.000239" iyz="0.0"
                        izz="0.000044" />
            </inertial>

        </link>

        <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
            <parent link="chassis"/>
            <child link="${prefix}_${suffix}_wheel"/>
            <origin xyz="${offset_x} ${offset_y} ${offset_z}" rpy="-${pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>

        <gazebo reference="${prefix}_${suffix}_wheel">
            <material>Gazebo/Orange</material>
        </gazebo>   

        <gazebo reference="${prefix}_${suffix}_roller">
            <mu1>100000000000000.0</mu1>
            <mu2>100000000000000.0</mu2>
        </gazebo>

        <xacro:roller prefix="${prefix}_${suffix}" suffix="one" theta="${2*pi*(1/10)}" roller_orientation="${wheel_roller_orientation}"/>
        <xacro:roller prefix="${prefix}_${suffix}" suffix="two" theta="${2*pi*(2/10)}" roller_orientation="${wheel_roller_orientation}"/>
        <xacro:roller prefix="${prefix}_${suffix}" suffix="thr" theta="${2*pi*(3/10)}" roller_orientation="${wheel_roller_orientation}"/>
        <xacro:roller prefix="${prefix}_${suffix}" suffix="for" theta="${2*pi*(4/10)}" roller_orientation="${wheel_roller_orientation}"/>
        <xacro:roller prefix="${prefix}_${suffix}" suffix="fve" theta="${2*pi*(5/10)}" roller_orientation="${wheel_roller_orientation}"/>
        <xacro:roller prefix="${prefix}_${suffix}" suffix="six" theta="${2*pi*(6/10)}" roller_orientation="${wheel_roller_orientation}"/>
        <xacro:roller prefix="${prefix}_${suffix}" suffix="svn" theta="${2*pi*(7/10)}" roller_orientation="${wheel_roller_orientation}"/>
        <xacro:roller prefix="${prefix}_${suffix}" suffix="ate" theta="${2*pi*(8/10)}" roller_orientation="${wheel_roller_orientation}"/>
        <xacro:roller prefix="${prefix}_${suffix}" suffix="nne" theta="${2*pi*(9/10)}" roller_orientation="${wheel_roller_orientation}"/>
        <xacro:roller prefix="${prefix}_${suffix}" suffix="ten" theta="${2*pi*(10/10)}" roller_orientation="${wheel_roller_orientation}"/>
    </xacro:macro>

</robot>