<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >    

    <!-- Chassis measures -->
    <xacro:property name="chassis_length" value="0.297"/>
    <xacro:property name="chassis_width" value="0.188"/>
    <xacro:property name="chassis_height" value="0.09"/>
    <!-- In rviz the X axis is red, the Y axis green and the Z axis blue -->

    <!-- Wheels measures -->
    <xacro:property name="wheel_offset_y" value="${chassis_width/2 + 0.025}"/>
    <xacro:property name="wheel_offset_x" value="${chassis_length/2 - 0.051}"/>
    <xacro:property name="wheel_offset_z" value="0.028"/>
    <xacro:property name="wheel_radius" value="0.0375"/>

    <!-- Rollers measures -->
    <xacro:property name="roller_diameter" value="0,01"/>
    <xacro:property name="roller_length" value="0,01"/>
    
</robot>