<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rona">


    <!-- In this file the basic structure of the omnidirectional robot RONA is described -->

    <xacro:include filename="$(find simple_rona_robot)/simple_description/front_left_wheel.xacro"/>
    <xacro:include filename="$(find simple_rona_robot)/simple_description/front_right_wheel.xacro"/>
    <xacro:include filename="$(find simple_rona_robot)/simple_description/rear_left_wheel.xacro"/>
    <xacro:include filename="$(find simple_rona_robot)/simple_description/rear_right_wheel.xacro"/>
    <xacro:include filename="$(find simple_rona_robot)/simple_description/colors.xacro"/>
    <xacro:include filename="$(find simple_rona_robot)/simple_description/physical_properties.xacro"/>
    <!-- <xacro:include filename="$(find simple_rona_robot)/simple_description/rona_gazebo.xacro"/> -->

    <!-- ROBOT DESCRIPTION START -->

    <!-- Base link -->
    <link name="base_link">
    </link>

    <!-- Chassis -->
    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <box size="0.297 0.188 0.09"/>
            </geometry>
            <material name="blue"/>
        </collision>        
        
        <xacro:inertial_box mass="3" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 ${chassis_length}" rpy="0 0 0"/>
        </xacro:inertial_box>

    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0.022"/>
    </joint>

    <!-- Front left wheel -->
    <xacro:front_left_wheel/>

    <!-- Front right wheel -->
    <xacro:front_right_wheel/>

    <!-- Rear left wheel -->
    <xacro:rear_left_wheel/>
    
    <!-- Rear right wheel -->
    <xacro:rear_right_wheel/>
   
    <!-- ROBOT DESCRIPTION END -->    

</robot>
    
